name: Build Veins and create Release
run-name: ${{ gitea.actor }} release run
on:
  push:
    branches:
      - master
jobs: 
  Build-Container:
    runs-on: ubuntu-latest
    env: 
      ENV_FILE: .ci/versions.env
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: load env file
        run: |
          cat ${{ env.ENV_FILE }} >> $GITHUB_ENV          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
        config-inline: |
           [registry.${{ vars.CONTAINER_REGISTRY }}]           

      - name: Login at registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:.ci"
          file: Dockerfile
          platforms: |
            linux/amd64            
          push: true
          pull: true
          tags: ${{ vars.CONTAINER_REGISTRY }}veins:ciTest
          build-args: |
            OPP_VERSION=${{ env.OPP_VERSION }}
            SUMO_VERSION=${{ env.SUMO_VERSION }}
            INET_VERSION=${{ env.INET_VERSION }}            
            PUBLIC=FALSE

  TestVeins:
    needs: Build-Container
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ${{ vars.CONTAINER_REGISTRY }}veins:ciTest
      credentials:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Build veins
        run: |
          source /opt/omnetpp/setenv
          source /opt/inet/setenv
          source setenv
          ./configure
          make -j $(nproc)


