# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x06server\"\x1e\n\rScheduleInput\x12\r\n\x05input\x18\x01 \x01(\t\" \n\x0eScheduleOutput\x12\x0e\n\x06output\x18\x01 \x01(\t2N\n\tScheduler\x12\x41\n\x0e\x43reateSchedule\x12\x15.server.ScheduleInput\x1a\x16.server.ScheduleOutput\"\x00\x42#\n\x11\x63om.tsnsched.grpcB\x0cTSNschedgRPCP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.tsnsched.grpcB\014TSNschedgRPCP\001'
  _globals['_SCHEDULEINPUT']._serialized_start=27
  _globals['_SCHEDULEINPUT']._serialized_end=57
  _globals['_SCHEDULEOUTPUT']._serialized_start=59
  _globals['_SCHEDULEOUTPUT']._serialized_end=91
  _globals['_SCHEDULER']._serialized_start=93
  _globals['_SCHEDULER']._serialized_end=171
# @@protoc_insertion_point(module_scope)
